import type { z } from "zod";
import {
  BookGroundRequest,
  BookGroundResponse,
  BookSearchRequest,
  BookSearchResponse,
} from "./book.js";
import { ListPlansResponse, PlanGenerateRequest, PlanResponse } from "./plan.js";
import {
  QuizCheckRequest,
  QuizCheckResponse,
  QuizGenerateRequest,
  QuizInstance,
  QuizSubmitRequest,
  QuizSubmitResponse,
} from "./quiz.js";
import { AdminGroundingResponse, AdminOverrideRequest } from "./grounding.js";
import {
  AdminMetricsResponse,
  AdminPlansResponse,
  AdminPushTestRequest,
  AdminPushTestResponse,
  AdminQuizInvalidateRequest,
  AdminQuizInvalidateResponse,
  AdminQuizzesResponse,
  AdminTtsResponse,
} from "./admin.js";
import {
  AddLibraryBookRequest,
  LibraryBook,
  LibraryBooksResponse,
  PushRegisterRequest,
  StepStartResponse,
  TtsGenerateRequest,
  TtsGenerateResponse,
} from "./misc.js";
import { MyStatsResponse } from "./stats.js";
import {
  AdminAccountActionResponse,
  AdminLoginRequest,
  AdminLoginResponse,
  AdminMeResponse,
  AdminPendingAccountsResponse,
  AdminSignupRequest,
  AdminSignupResponse,
} from "./admin-auth.js";
import {
  AdminAiModelsResponse,
  AdminSettingsResponse,
  AdminUpdateSettingRequest,
  AdminUpdateSettingResponse,
} from "./settings.js";

export type HttpMethod = "get" | "post" | "put" | "delete";

export interface EndpointDef {
  method: HttpMethod;
  /** Express-style path with `:param`. Converted to `{param}` for OpenAPI. */
  path: string;
  operationId: string;
  summary: string;
  tag: string;
  auth: "user" | "admin" | "admin_panel" | "none";
  request?: z.ZodType;
  response?: z.ZodType;
}

/**
 * The single source of truth for the HTTP surface. Both the Fastify server and
 * the OpenAPI generator read this list, so the spec cannot drift from the code.
 */
export const ENDPOINTS: readonly EndpointDef[] = [
  {
    method: "post",
    path: "/v1/books/search",
    operationId: "searchBooks",
    summary: "Deterministic Google Books + Open Library search and candidate merge.",
    tag: "books",
    auth: "user",
    request: BookSearchRequest,
    response: BookSearchResponse,
  },
  {
    method: "post",
    path: "/v1/books/ground",
    operationId: "groundBook",
    summary: "Gemini Search Grounding enrichment / edition reconciliation.",
    tag: "books",
    auth: "user",
    request: BookGroundRequest,
    response: BookGroundResponse,
  },
  {
    method: "get",
    path: "/v1/library/books",
    operationId: "listLibraryBooks",
    summary: "List the authenticated user's library books.",
    tag: "library",
    auth: "user",
    response: LibraryBooksResponse,
  },
  {
    method: "post",
    path: "/v1/library/books",
    operationId: "addLibraryBook",
    summary: "Add a grounded book to the user's library.",
    tag: "library",
    auth: "user",
    request: AddLibraryBookRequest,
    response: LibraryBook,
  },
  {
    method: "get",
    path: "/v1/me/stats",
    operationId: "getMyStats",
    summary: "Streaks, XP, and the trailing 7-day reading window for the caller.",
    tag: "stats",
    auth: "user",
    response: MyStatsResponse,
  },
  {
    method: "get",
    path: "/v1/plans",
    operationId: "listPlans",
    summary: "List the caller's plans (newest planVersion first). Filter with `?bookId=`.",
    tag: "plans",
    auth: "user",
    response: ListPlansResponse,
  },
  {
    method: "post",
    path: "/v1/plans/generate",
    operationId: "generatePlan",
    summary: "Create or refresh a nightly reading path.",
    tag: "plans",
    auth: "user",
    request: PlanGenerateRequest,
    response: PlanResponse,
  },
  {
    method: "get",
    path: "/v1/plans/:id",
    operationId: "getPlan",
    summary: "Fetch a plan and its step states.",
    tag: "plans",
    auth: "user",
    response: PlanResponse,
  },
  {
    method: "post",
    path: "/v1/steps/:id/start",
    operationId: "startStep",
    summary: "Open (or reuse) a reading session for a step.",
    tag: "steps",
    auth: "user",
    response: StepStartResponse,
  },
  {
    method: "post",
    path: "/v1/steps/:id/quiz",
    operationId: "generateStepQuiz",
    summary: "Generate or fetch tonight's quiz for a step.",
    tag: "quiz",
    auth: "user",
    request: QuizGenerateRequest,
    response: QuizInstance,
  },
  {
    method: "post",
    path: "/v1/quiz/:id/check",
    operationId: "checkQuizAnswer",
    summary: "Instant per-question feedback (does not record an attempt or affect streak).",
    tag: "quiz",
    auth: "user",
    request: QuizCheckRequest,
    response: QuizCheckResponse,
  },
  {
    method: "post",
    path: "/v1/quiz/:id/submit",
    operationId: "submitQuiz",
    summary: "Score answers, mark the reading complete, update streak.",
    tag: "quiz",
    auth: "user",
    request: QuizSubmitRequest,
    response: QuizSubmitResponse,
  },
  {
    method: "post",
    path: "/v1/push/register",
    operationId: "registerPushToken",
    summary: "Register or update a device push token.",
    tag: "push",
    auth: "user",
    request: PushRegisterRequest,
  },
  {
    method: "post",
    path: "/v1/tts/generate",
    operationId: "generateTts",
    summary: "Request background TTS generation (hash-deduped + cached).",
    tag: "tts",
    auth: "user",
    request: TtsGenerateRequest,
    response: TtsGenerateResponse,
  },
  {
    method: "post",
    path: "/v1/admin/books/search",
    operationId: "adminSearchBooks",
    summary: "Admin-scoped catalog search (same deterministic search as searchBooks, gated by admin_panel session instead of a user JWT).",
    tag: "admin",
    auth: "admin_panel",
    request: BookSearchRequest,
    response: BookSearchResponse,
  },
  {
    method: "get",
    path: "/v1/admin/books/:id/grounding",
    operationId: "adminGetGrounding",
    summary: "Inspect grounding sources, facts, and diffs for a book.",
    tag: "admin",
    auth: "admin_panel",
    response: AdminGroundingResponse,
  },
  {
    method: "post",
    path: "/v1/admin/books/:id/override",
    operationId: "adminOverrideBook",
    summary: "Manual correction / trust lock on a book's grounded fields.",
    tag: "admin",
    auth: "admin_panel",
    request: AdminOverrideRequest,
  },
  {
    method: "get",
    path: "/v1/admin/metrics",
    operationId: "adminGetMetrics",
    summary: "Dashboard tiles: grounding buckets, quiz pass rate, TTS assets, book count.",
    tag: "admin",
    auth: "admin_panel",
    response: AdminMetricsResponse,
  },
  {
    method: "get",
    path: "/v1/admin/tts",
    operationId: "adminGetTts",
    summary: "List cached TTS assets for the cache inspector.",
    tag: "admin",
    auth: "admin_panel",
    response: AdminTtsResponse,
  },
  {
    method: "post",
    path: "/v1/admin/quiz/:id/invalidate",
    operationId: "adminInvalidateQuiz",
    summary: "Mark a quiz invalid so it is not reused; records a reason.",
    tag: "admin",
    auth: "admin_panel",
    request: AdminQuizInvalidateRequest,
    response: AdminQuizInvalidateResponse,
  },
  {
    method: "get",
    path: "/v1/admin/plans",
    operationId: "adminListPlans",
    summary: "List reading plans (newest first) with derived step counts. `?limit=`.",
    tag: "admin",
    auth: "admin_panel",
    response: AdminPlansResponse,
  },
  {
    method: "get",
    path: "/v1/admin/quizzes",
    operationId: "adminListQuizzes",
    summary: "List quiz instances with derived question counts. `?stepId=&limit=`.",
    tag: "admin",
    auth: "admin_panel",
    response: AdminQuizzesResponse,
  },
  {
    method: "post",
    path: "/v1/admin/push/test",
    operationId: "adminTestPush",
    summary: "Send a test push of a given type to a user's registered device tokens.",
    tag: "admin",
    auth: "admin_panel",
    request: AdminPushTestRequest,
    response: AdminPushTestResponse,
  },
  {
    method: "post",
    path: "/v1/admin/auth/signup",
    operationId: "adminSignup",
    summary: "Request an admin-panel account (@mytsi.org only; requires approval).",
    tag: "admin-auth",
    auth: "none",
    request: AdminSignupRequest,
    response: AdminSignupResponse,
  },
  {
    method: "post",
    path: "/v1/admin/auth/login",
    operationId: "adminLogin",
    summary: "Log in to the admin panel; returns an opaque session token.",
    tag: "admin-auth",
    auth: "none",
    request: AdminLoginRequest,
    response: AdminLoginResponse,
  },
  {
    method: "post",
    path: "/v1/admin/auth/logout",
    operationId: "adminLogout",
    summary: "Revoke the caller's admin session.",
    tag: "admin-auth",
    auth: "admin_panel",
  },
  {
    method: "get",
    path: "/v1/admin/auth/me",
    operationId: "adminMe",
    summary: "Resolve the current admin-panel session.",
    tag: "admin-auth",
    auth: "admin_panel",
    response: AdminMeResponse,
  },
  {
    method: "get",
    path: "/v1/admin/accounts/pending",
    operationId: "adminListPendingAccounts",
    summary: "List admin-panel accounts awaiting approval.",
    tag: "admin-auth",
    auth: "admin_panel",
    response: AdminPendingAccountsResponse,
  },
  {
    method: "post",
    path: "/v1/admin/accounts/:id/approve",
    operationId: "adminApproveAccount",
    summary: "Approve a pending admin-panel account.",
    tag: "admin-auth",
    auth: "admin_panel",
    response: AdminAccountActionResponse,
  },
  {
    method: "post",
    path: "/v1/admin/accounts/:id/reject",
    operationId: "adminRejectAccount",
    summary: "Reject a pending admin-panel account.",
    tag: "admin-auth",
    auth: "admin_panel",
    response: AdminAccountActionResponse,
  },
  {
    method: "get",
    path: "/v1/admin/settings",
    operationId: "adminGetSettings",
    summary: "List every admin-editable setting (secrets masked).",
    tag: "settings",
    auth: "admin_panel",
    response: AdminSettingsResponse,
  },
  {
    method: "put",
    path: "/v1/admin/settings/:key",
    operationId: "adminPutSetting",
    summary: "Update one setting by key, validated against its per-key schema.",
    tag: "settings",
    auth: "admin_panel",
    request: AdminUpdateSettingRequest,
    response: AdminUpdateSettingResponse,
  },
  {
    method: "get",
    path: "/v1/admin/ai/models",
    operationId: "adminGetAiModels",
    summary: "Live model catalog for a given provider. `?provider=groq|openrouter`.",
    tag: "settings",
    auth: "admin_panel",
    response: AdminAiModelsResponse,
  },
] as const;
